#!/bin/bash
#PBS -N subcounts
#PBS -q avx
#PBS -l nodes=2:ppn=32
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID


export PATH=/usr/local/bin:$PATH
TYPE=$1
FILE=$2


PROJPATH=/home/sjspielman/leisr_rates_across_models
DATAPATH=$PROJPATH/data/${TYPE}
RESULTPATH=$PROJPATH/count_subs/$TYPE-inference
mkdir -p $RESULTPATH


HYPATH=/home/sjspielman/hyphy
MPI=$HYPATH/HYPHYMPI
LIBPATH=$HYPATH/res
BATCHFILE=$LIBPATH/TemplateBatchFiles/leisr2.bf ## just fits global models and spits back counts
RV=No
for MODEL in LG WAG JTT JC69 gcpREV mtMet HIVBm; do
    OUTFILE=$RESULTPATH/$FILE.$MODEL-$RV-subcounts.txt
    if [ ! -e $OUTFILE ]; then
        /opt/scyld/openmpi/1.6.3/gnu/bin/mpirun -np 64 $MPI LIBPATH=$LIBPATH $BATCHFILE ${DATAPATH}/$FILE y Protein $MODEL $RV $OUTFILE
    fi
done
