#!/bin/bash
#PBS -N perturbedbl
#PBS -q avx
#PBS -l nodes=2:ppn=32
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID


export PATH=/usr/local/bin:$PATH
NAME=$1
X=$2

PROJPATH=/home/sjspielman/leisr_rates_across_models
DATAPATH=$PROJPATH/data/enzyme_data_permuted_bl
RESULTPATH=$PROJPATH/rate_inference_branch_lengths/perturbed_inference
mkdir -p $RESULTPATH


HYPATH=/home/sjspielman/hyphy
MPI=$HYPATH/HYPHYMPI
LIBPATH=$HYPATH/res
BATCHFILE=$LIBPATH/TemplateBatchFiles/LEISR.bf

CONSTRAINT=input
FILE=${NAME}_permuted_bl_${X}.fna
for MODEL in LG WAG JC69; do        
    JSON=$RESULTPATH/$FILE.$MODEL.LEISR.json
    if [ ! -e $JSON ]; then
        /opt/scyld/openmpi/1.6.3/gnu/bin/mpirun -np 64 $MPI LIBPATH=$LIBPATH $BATCHFILE ${DATAPATH}/$FILE y Protein $MODEL No
        mv ${DATAPATH}/$FILE.LEISR.json $JSON
    fi
done
