#!/bin/bash
#PBS -N treepipe
#PBS -q avx
#PBS -l nodes=2:ppn=32
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID


export PATH=/usr/local/bin:$PATH

NAME=$1      ##### dataset
TREEMODEL=$2 ##### JC69, WAG, LG, JTT


PROJPATH=/home/sjspielman/leisr_rates_across_models
DATAPATH=$PROJPATH/data/fasta
PIPEPATH=$PROJPATH/pipeline_model_trees
TREEPATH=$PIPEPATH/raxmltrees
RESULTPATH=$PIPEPATH/rate_inference
mkdir -p $RESULTPATH

HYPATH=/home/sjspielman/hyphy
MPI=$HYPATH/HYPHYMPI
LIBPATH=$HYPATH/res
BATCHFILE=$LIBPATH/TemplateBatchFiles/LEISR.bf


TREEFILE=${TREEPATH}/${NAME}_${TREEMODEL}tree.tre
FNA=${RESULTPATH}/${NAME}_${TREEMODEL}tree.fna
FASTA=${DATAPATH}/${NAME}.fasta

FNA=${RESULTPATH}/${NAME}_${TREEMODEL}tree.fna
cat $FASTA $TREEFILE > $FNA

#### rate inference under a few models ####
for RATEMODEL in JC69 WAG LG JTT; do
    JSON=${FNA}.${RATEMODEL}.LEISR.json
    if [ ! -e $JSON ]; then
        /opt/scyld/openmpi/1.6.3/gnu/bin/mpirun -np 64 $MPI LIBPATH=$LIBPATH $BATCHFILE $FNA y Protein $RATEMODEL No
        mv $FNA.LEISR.json $JSON
    fi
done

