#!/bin/bash
#PBS -N treepipe
#PBS -q avx
#PBS -l nodes=1:ppn=64
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID


export PATH=/usr/local/bin:$PATH

NAME=$1      ##### dataset
TREEMODEL=$2 ##### JC69, WAG, LG, JTT, MTMAM

CPU=64


PROJPATH=/home/sjspielman/leisr_rates_across_models
DATAPATH=$PROJPATH/data/fasta
PIPEPATH=$PROJPATH/pipeline_model_trees
RESULTPATH=$PIPEPATH/inference-${TREEMODEL}
mkdir -p $RESULTPATH

HYPATH=/home/sjspielman/hyphy
MP=$HYPATH/HYPHYMP
LIBPATH=$HYPATH/res
BATCHFILE=$LIBPATH/TemplateBatchFiles/LEISR.bf



##### raxml tree ######
TREEMODELRAX=PROTCAT${TREEMODEL}F
FASTA=${DATAPATH}/${NAME}.fasta
if [ $TREEMODEL == "JC69" ]; then
    /home/sjspielman/bin/raxmlHPC-PTHREADS-SSE3 -T $CPU -p 101188 -s $FASTA -m $TREEMODELRAX -P $PIPEPATH/jc69.raxmat -n $TREEMODEL
else
    /home/sjspielman/bin/raxmlHPC-PTHREADS-SSE3 -T $CPU -p 101188 -s $FASTA -m $TREEMODELRAX -n $TREEMODEL
fi

TREEFILE=${NAME}_${TREEMODEL}.tre
FNA=${NAME}_${TREEMODEL}.fna
mv RAxML_bestTree.$TREEMODEL $TREEFILE
cat $FASTA $TREEFILE > $FNA

#### rate inference under a few models ####
for RATEMODEL in JC69 WAG LG JTT MTMAM;
    JSON=$RESULTPATH/${NAME}_${TREEMODEL}.fna.${RATEMODEL}.LEISR.json
        if [ ! -e $JSON ]; then
            MP CPU=$CPU LIBPATH=$LIBPATH $BATCHFILE $FNA y Protein $RATEMODEL No
            mv $FNA.LEISR.json $JSON
       fi
    done
done

