#!/bin/bash
#PBS -N trees
#PBS -q avx
#PBS -l nodes=1:ppn=64
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID


export PATH=/usr/local/bin:$PATH

NAME=$1      ##### dataset
TREEMODEL=$2 ##### JC69, WAG, LG, JTT


PROJPATH=/home/sjspielman/leisr_rates_across_models
DATAPATH=$PROJPATH/data/fasta
PIPEPATH=$PROJPATH/pipeline_model_trees
JCPATH=$PIPEPATH/jc69raxmat
RESULTPATH=$PIPEPATH/raxmltrees
mkdir -p $RESULTPATH

cd $RESULTPATH

##### raxml tree ######
SUFFIX=$TREEMODEL-$NAME
TREEMODELRAX=PROTCAT${TREEMODEL}F
FASTA=${DATAPATH}/${NAME}.fasta
if [ $TREEMODEL == "JC69" ]; then
    JCRAXMAT=${JCPATH}/JC69_${NAME}.raxmat
    /home/sjspielman/bin/raxmlHPC-PTHREADS-AVX  -T 64 -p 101188 -s $FASTA -m PROTCATLGF -P $JCRAXMAT -n $SUFFIX
else
    /home/sjspielman/bin/raxmlHPC-PTHREADS-AVX -T 64 -p 101188 -s $FASTA -m $TREEMODELRAX -n $SUFFIX
fi

TREEFILE=${NAME}_${TREEMODEL}tree.tre
FNA=${NAME}_${TREEMODEL}tree.fna
mv RAxML_bestTree.$SUFFIX ${RESULTPATH}/$TREEFILE
mv RAxML_info.$SUFFIX ${RESULTPATH}/${NAME}_${TREEMODEL}tree_raxmlinfo.txt

rm rm RAxML*${NAME}

