#!/bin/bash
#PBS -N treepipe
#PBS -q avx
#PBS -l nodes=1:ppn=64
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID


export PATH=/usr/local/bin:$PATH

NAME=$1      ##### dataset
TREEMODEL=$2 ##### JC69, WAG, LG, JTT

CPU=64


PROJPATH=/home/sjspielman/leisr_rates_across_models
DATAPATH=$PROJPATH/data/fasta
PIPEPATH=$PROJPATH/pipeline_model_trees
JCPATH=$PIPEPATH/jc69raxmat
RESULTPATH=$PIPEPATH/inference-${TREEMODEL}
mkdir -p $RESULTPATH

HYPATH=/home/sjspielman/hyphy
MP=$HYPATH/HYPHYMP
LIBPATH=$HYPATH/res
BATCHFILE=$LIBPATH/TemplateBatchFiles/LEISR.bf



##### raxml tree ######
SUFFIX=$TREEMODEL-$NAME
TREEMODELRAX=PROTCAT${TREEMODEL}F
FASTA=${DATAPATH}/${NAME}.fasta
if [ $TREEMODEL == "JC69" ]; then
    JCRAXMAT=${JCPATH}/JC69_${NAME}.raxmat
    /home/sjspielman/bin/raxmlHPC-PTHREADS-SSE3 -T $CPU -p 101188 -s $FASTA -m PROTCATLGF -P $JCRAXMAT -n $SUFFIX
else
    /home/sjspielman/bin/raxmlHPC-PTHREADS-SSE3 -T $CPU -p 101188 -s $FASTA -m $TREEMODELRAX -n $SUFFIX
fi

TREEFILE=${NAME}_${TREEMODEL}tree.tre
FNA=${NAME}_${TREEMODEL}tree.fna
mv RAxML_bestTree.$SUFFIX ${RESULTPATH}/$TREEFILE
mv RAxML_info.$SUFFIX ${RESULTPATH}/${NAME}_${TREEMODEL}tree_raxmlinfo.txt

rm ~/RAxML_*

cd $RESULTPATH
cat $FASTA $TREEFILE > $FNA

#### rate inference under a few models ####
for RATEMODEL in JC69 WAG LG JTT; do
    JSON=$RESULTPATH/${FNA}.${RATEMODEL}.LEISR.json
    if [ ! -e $JSON ]; then
        $MP CPU=$CPU LIBPATH=$LIBPATH $BATCHFILE ${RESULTPATH}/$FNA y Protein $RATEMODEL No
        mv $FNA.LEISR.json $JSON
    fi
done

