#!/bin/bash
#PBS -N randomtree
#PBS -q avx
#PBS -l nodes=2:ppn=32
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID



export PATH=/usr/local/bin:$PATH
NAME=$1

PROJPATH=/home/sjspielman/leisr_rates_across_models
DATAPATH=$PROJPATH/data/random_trees
RESULTPATH=$PROJPATH/rate_inference_random_trees
mkdir -p $RESULTPATH



HYPATH=/home/sjspielman/hyphy
MPI=$HYPATH/HYPHYMPI
LIBPATH=$HYPATH/res
BATCHFILE=$LIBPATH/TemplateBatchFiles/LEISR.bf
RV=No

for X in {1..10}; do
    FILE=${NAME}_random_tree_${X}.fna
    for MODEL in LG WAG JC69; do
        JSON=$RESULTPATH/${NAME}_randomtree_${X}.$MODEL.LEISR.json
        if [ ! -e $JSON ]; then
            /opt/scyld/openmpi/1.6.3/gnu/bin/mpirun -np 64 $MPI LIBPATH=$LIBPATH  $BATCHFILE ${DATAPATH}/$FILE y Protein $MODEL $RV
            mv ${DATAPATH}/$FILE.LEISR.json $JSON
        fi
    done
done
