#!/bin/bash
#PBS -N randomEFV
#PBS -q avx
#PBS -l nodes=2:ppn=32
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID



export PATH=/usr/local/bin:$PATH
NAME=$1

PROJPATH=/home/sjspielman/leisr_rates_across_models
DATAPATH=$PROJPATH/data/enzyme_data
RESULTPATH=$PROJPATH/rate_inference_random_EFV
mkdir -p $RESULTPATH



HYPATH=/home/sjspielman/hyphy
MPI=$HYPATH/HYPHYMPI
LIBPATH=$HYPATH/res
BATCHFILE=$RESULTPATH/LEISR_randomEFV.bf
RV=No

FILE=${NAME}.fna
for X in {1..10}; do
    for MODEL in LG WAG JC69; do
        JSON=$RESULTPATH/${NAME}_randEFV_${X}.${MODEL}.LEISR.json
        if [ ! -e $JSON ]; then
            /opt/scyld/openmpi/1.6.3/gnu/bin/mpirun -np 64 $MPI LIBPATH=$LIBPATH  $BATCHFILE ${DATAPATH}/$FILE y Protein $MODEL $RV
            mv ${DATAPATH}/$FILE.LEISR.json $JSON
        fi
    done
done
