#!/bin/bash
#PBS -N singlealnmatrix
#PBS -q avx
#PBS -l nodes=1:ppn=64
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID


export PATH=/usr/local/bin:$PATH


WDIR=/home/sjspielman/leisr_rates_across_models/matrix_inference

LIBPATH=${WDIR}/hyphy/res
MP=${WDIR}/hyphy/HYPHYMP
BATCHFILE=${LIBPATH}/TemplateBatchFiles/ProteinGTRFit.bf


$MP LIBPATH=$LIBPATH $BATCHFILE $WDIR/rpoC1.list
